title: Jared Thompson

description: jaredthompson05@yahoo.com

description: [LinkedIn](www.linkedin.com/in/jared-thompson-b9995420a)

logo: <img src= "B6CAAC66-D752-4838-8837-A4B90C4D0AA3 Small.jpeg" width="32" height="32">

theme: jekyll-theme-cayman
